"""fk cascade and defaults

Revision ID: 3772b5e709f5
Revises: 2ff99f48aeb2
Create Date: 2025-12-26 19:39:55.815583

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '3772b5e709f5'
down_revision = '2ff99f48aeb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('url_daily_stats', 'url_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_constraint(op.f('url_daily_stats_url_id_fkey'), 'url_daily_stats', type_='foreignkey')
    op.create_foreign_key(None, 'url_daily_stats', 'urls', ['url_id'], ['id'], ondelete='CASCADE')
    op.alter_column('url_visits', 'url_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_constraint(op.f('url_visits_url_id_fkey'), 'url_visits', type_='foreignkey')
    op.create_foreign_key(None, 'url_visits', 'urls', ['url_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'url_visits', type_='foreignkey')
    op.create_foreign_key(op.f('url_visits_url_id_fkey'), 'url_visits', 'urls', ['url_id'], ['id'])
    op.alter_column('url_visits', 'url_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'url_daily_stats', type_='foreignkey')
    op.create_foreign_key(op.f('url_daily_stats_url_id_fkey'), 'url_daily_stats', 'urls', ['url_id'], ['id'])
    op.alter_column('url_daily_stats', 'url_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
