"""init schema

Revision ID: 2ff99f48aeb2
Revises: 
Create Date: 2025-12-26 19:28:16.279459

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2ff99f48aeb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('short_code', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('visit_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('last_visited_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_urls_created_at', 'urls', ['created_at'], unique=False)
    op.create_index(op.f('ix_urls_short_code'), 'urls', ['short_code'], unique=True)
    op.create_table('url_daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('count', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_id', 'day', name='uq_url_daily_stats_url_id_day')
    )
    op.create_index('ix_url_daily_stats_url_id_day', 'url_daily_stats', ['url_id', 'day'], unique=False)
    op.create_table('url_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('visited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_url_visits_url_id_visited_at', 'url_visits', ['url_id', 'visited_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_url_visits_url_id_visited_at', table_name='url_visits')
    op.drop_table('url_visits')
    op.drop_index('ix_url_daily_stats_url_id_day', table_name='url_daily_stats')
    op.drop_table('url_daily_stats')
    op.drop_index(op.f('ix_urls_short_code'), table_name='urls')
    op.drop_index('ix_urls_created_at', table_name='urls')
    op.drop_table('urls')
    # ### end Alembic commands ###
